version: "3"
services:
  portainer_ce:
    container_name: portainer_ce
    image: portainer/portainer-ce:latest
    ports:
      - 9444:9444
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  data: